### PR TITLE
Garage door opener support MSG100

### PR DESCRIPTION
**Pull request by STDevMan**
I'll test this out a bit more, but it works so far. The UUID might only be needed on the meross main settings, not sure yet

### CODE REVIEW

**Comment by dehsgr** [comment]
@STDevMan very cool! Thanks for contributing. I'll suspend merge until
- you finalized your tests and get are more safe about UUID usage.
- perform some small corrections to text on Readme.md:

> **Meross Config**
> Meross Config is a config node to set the token, message id, timestamp (and UUID for Garage Door) being able to locally communicate with your devices.

> **Currently supported devices**
> - Meross Smart Plug MSS210(EU)
> - Meross Garage <ins><strong>D</strong></ins>oor MSG100 

Text corrections are cosmetically and I hope there is okay to you. :-)

**Comment by STDevMan** [comment]
no problem. I will make the recommended changes. 

I did some more testing and it looks like UUID isn't actually needed when making calls locally with an existing messageId and timestamp. I think it is required for meross cloud requests. It doesn't hurt to leave in UUID though but it can be any value. I tested with "uuid=hello" and it worked locally. I will add some code to randomly generate a size 16 hex string in case the code is reused for cloud stuff.

also I don't think the garage state call is working either, so I will get that working

**Comment by STDevMan** [comment]
all files updated and tested in my main repo for Garage Door MSG100

**Comment by dehsgr** [comment]
Well done! I'll just published v1.1.0 to NPM. Thanks again! ;-)

**Pull request merged**
